### ISSUE TITLE
LinkedIn Sign-In outdated since Linkedin API upgrade in oct-nov 2023

### ISSUE THREAD

**Issue by noamwak** [humhub/auth-linkedin#4]
Hi,

LinkedIn scopes r_liteprofile & r_emailaddress are deprecated and no longer work with new LinkedIn apps.
These scopes are not supported with new LinkedIn apps.

Will you update your module with the Linkedin apps requirements?

Thanks for your help

**Comment by luke-** [comment]
@gevorgmansuryan Thanks!

@noamwak Can you please check module version 1.1.0?

**Comment by noamwak** [comment]
Thank you very much, @luke- ! At the moment, I don't see any errors, and I was able to authenticate without any issues. I will let you know if I encounter any error messages.
